### ISSUE TITLE
robot_mitigation

### ISSUE THREAD

**Issue by 290557551** [NeusoftSecurity/SEnginx#39]
robot_mitigation_challenge_ajax
语法	robot_mitigation_challenge_ajax on/off;
默认值	off
上下文	Location
有效版本	1.5.5及以后版本

默认是off，但merge时，却是on;
 ngx_conf_merge_value(conf->pass_ajax, prev->pass_ajax, 1);

**Comment by InfoHunter** [comment]
呵呵

**Comment by 290557551** [comment]
文档与代码多处不一致，再举两个:
如：
robot_mitigation_blacklist
语法	robot_mitigation_blacklist failed_count
默认值	5
上下文	Location
设置黑名单失败次数上限

文档默认5， 代码却是-1


再如:
robot_mitigation_timeout
语法	robot_mitigation_timeout timeout
默认值	60
上下文	Location
设置挑战成功后的有效时间，超过这个时间后，会重新发起挑战，单位是秒

文档默认60， 代码却是600

**Comment by InfoHunter** [comment]
有此问题？能发个pull request么？

**Comment by 290557551** [comment]
上午只看了robot_mitigation模块，没统计有多少，只是举两个例子。等有时间，一次性pull上去。

**Comment by InfoHunter** [comment]
OK
