### ISSUE TITLE
动态ip黑名单，工作模式为sys，执行失败

### ISSUE THREAD

**Issue by herono2010** [NeusoftSecurity/SEnginx#54]
我的环境是Linux ubuntu 3.13.0-32-generic，编译完SEngix, 用Robot Mitigation模块和动态IP黑名单实现动态黑名单功能，当动态ip黑名单工作模式为sys时候，配置命令为 ip_blacklist_syscmd "sudo /sbin/iptables -A INPUT -s %V -j DROP";  用gdb调试的时候，发现在ngx_http_ip_blacklist.c:ngx_http_ip_blacklist_update()函数，执行到1013行，ret = system((char *)imcf->buf);不管ret返回256还是0，配置里面的命令都没有执行成功，紧急求助！！！

**Comment by InfoHunter** [comment]
@skyever

**Comment by herono2010** [comment]
问题已经解决，是配置文件中应该添加配置项user  root;，不然SEnginx调用system()系统函数执行不成功，再次谢谢开发者。
